# Novela settings
baseURL = "https://daniel-livingston.com/"
theme = "novela"
languageCode = "en-us"
title = "Daniel Livingston"

paginate = 6

[social]
github = "https://github.com/daniellivingston"
linkedin = "https://www.linkedin.com/in/danielrlivingston/"
instagram = "https://www.instagram.com/liv.ing.ston/"
#telegram = "sgsdfgs"
#500px = "sgsdfgs"
#orchid = "sgsdfgs"

[taxonomies]
author = "authors"
