# Novela settings
baseURL = "https://daniel-livingston.com/"
theme = "novela"
languageCode = "en-us"
title = "Daniel Livingston"

paginate = 6

[social]
github = "https://github.com/forestryio/novela-hugo-starter"
linkedin = "https://www.linkedin.com/company/forestry.io"
instagram = "#"

[taxonomies]
author = "authors"
